
version: '3'

networks:
    vue:
    
services:
    run_app:
        build:
            context: .
            dockerfile : Dockerfile
        ports:
            - "8080:8085"        
        volumes:
            - .:/app
        networks:
            - vue 
            